name = "base-engineering"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Production Cloudflare D1 Database binding
[[d1_databases]]
binding = "base_db"
database_name = "base_db"
database_id = "f4637272-eb53-4297-bf30-b47a819e52bc"
migrations_dir = "migrations"

# Cloudflare R2 Storage Bucket binding
[[r2_buckets]]
binding = "BASE_ENG_BUCKET"
bucket_name = "base-engineering-assets"
